// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mR4rK1Bw5DYg6UzrkHpn82ehKyAEPWk',
    appId: '1:718038998479:web:0dbeb3b36b88025b6106ba',
    messagingSenderId: '718038998479',
    projectId: 'fruit-hub-2905d',
    authDomain: 'fruit-hub-2905d.firebaseapp.com',
    storageBucket: 'fruit-hub-2905d.firebasestorage.app',
    measurementId: 'G-FNCD9L06ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqVT_HBEMGX90DT6axHnQPFwiNWDGjz0',
    appId: '1:718038998479:android:0f0f8f4d6f8cbfe36106ba',
    messagingSenderId: '718038998479',
    projectId: 'fruit-hub-2905d',
    storageBucket: 'fruit-hub-2905d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy02pSKrL7kXZGH33Sq_OqmGFXFwJZgsY',
    appId: '1:718038998479:ios:e4674db4c5ec3d5c6106ba',
    messagingSenderId: '718038998479',
    projectId: 'fruit-hub-2905d',
    storageBucket: 'fruit-hub-2905d.firebasestorage.app',
    androidClientId: '718038998479-uo6gq3qg5gn3180n47ap1fi3gq6rdt1b.apps.googleusercontent.com',
    iosClientId: '718038998479-k8iv2rj8rof1vt54ohs2c15ev28j1k56.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy02pSKrL7kXZGH33Sq_OqmGFXFwJZgsY',
    appId: '1:718038998479:ios:e4674db4c5ec3d5c6106ba',
    messagingSenderId: '718038998479',
    projectId: 'fruit-hub-2905d',
    storageBucket: 'fruit-hub-2905d.firebasestorage.app',
    androidClientId: '718038998479-uo6gq3qg5gn3180n47ap1fi3gq6rdt1b.apps.googleusercontent.com',
    iosClientId: '718038998479-k8iv2rj8rof1vt54ohs2c15ev28j1k56.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8mR4rK1Bw5DYg6UzrkHpn82ehKyAEPWk',
    appId: '1:718038998479:web:feb85369b5afaae76106ba',
    messagingSenderId: '718038998479',
    projectId: 'fruit-hub-2905d',
    authDomain: 'fruit-hub-2905d.firebaseapp.com',
    storageBucket: 'fruit-hub-2905d.firebasestorage.app',
    measurementId: 'G-KN01V4ZFRE',
  );
}
